[package]
name = "rustic"
version = "0.1.0"
authors = ["Marcel Vanthoor"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.7.3", features = ["small_rng"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
debug = true
rpath = false
debug-assertions = false
incremental = false
overflow-checks = false