[package]
name = "rustic"
version = "0.1.0"
authors = ["Marcel Vanthoor"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.7.3", features = ["small_rng"] }
if_chain = "1.0.0"
clap = "2.33.3"

[features]
extra = []

[profile.dev]
opt-level = 2
lto = false
codegen-units = 1
panic = 'unwind'
debug = true
debug-assertions = true
rpath = false
incremental = true
overflow-checks = false

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
debug = false
rpath = false
debug-assertions = false
incremental = false
overflow-checks = false